channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.8.1
  - alabaster=0.7.12
  - asn1crypto=1.3.0
  - astor=0.8.0
  - astroid=2.3.3
  - attrs=19.3.0
  - babel=2.8.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2021.1.19
  - cairo=1.14.12
  - certifi=2020.12.5
  - cffi=1.13.2
  - chardet=3.0.4
  - cloudpickle=1.2.2
  - cryptography=2.3.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cupti=10.0.130
  - curl=7.55.1
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.10.1
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - freexl=1.0.5
  - fribidi=1.0.5
  - gast=0.3.2
  - gdal=2.3.2
  - geos=3.6.2
  - giflib=5.1.4
  - glib=2.63.1
  - gmp=6.1.2
  - graphite2=1.3.13
  - graphviz=2.40.1
  - grpcio=1.14.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.6.1
  - imagesize=1.2.0
  - importlib_metadata=1.5.0
  - inflect=4.1.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jaraco.itertools=5.0.0
  - jasper=2.0.14
  - jedi=0.16.0
  - jeepney=0.4.2
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - kealib=1.4.7
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - keyring=21.1.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libboost=1.67.0
  - libcurl=7.61.1
  - libdap4=3.19.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=2.3.2
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libpq=10.5
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=3.0.5
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.18.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.3.0
  - openssl=1.0.2u
  - packaging=20.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.6.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=20.0.2
  - pixman=0.38.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - proj4=5.0.1
  - prompt_toolkit=3.0.3
  - protobuf=3.11.2
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pydot=1.4.1
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pylint=2.4.4
  - pyopenssl=19.0.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.0
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qt=5.9.6
  - qtawesome=0.6.1
  - qtconsole=4.6.0
  - qtpy=1.9.0
  - readline=7.0
  - requests=2.22.0
  - rope=0.16.0
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - scipy=1.4.1
  - secretstorage=3.1.2
  - setuptools=45.1.0
  - sip=4.19.8
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sphinx=2.3.1
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - spyder=3.3.6
  - spyder-kernels=0.5.1
  - sqlite=3.31.1
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - tensorflow-gpu=1.13.1
  - termcolor=1.1.0
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.32.1
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - wrapt=1.11.2
  - wurlitzer=2.0.0
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=2.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - astetik==1.9.8
    - chances==0.1.6
    - geonamescache==1.0.2
    - idna==2.10
    - kerasplotlib==0.1.4
    - matplotlib==2.2.3
    - pandas==0.25.0
    - patsy==0.5.1
    - savreaderwriter==3.4.2
    - seaborn==0.9.0
    - sklearn==0.0
    - statsmodels==0.10.1
    - talos==0.5.0
    - urllib3==1.25.3
    - wrangle==0.6.6

